/**
 * Design §35 portals + §36 account types → seeded IAM roles / gate permissions.
 * Not a parallel RBAC model: Super Admin still assigns permissions on Roles.
 * Extra seeded roles (GATE_OFFICER, CCTV_OPERATOR, …) map onto the nearest §36 account.
 */
export const DESIGN_ACCOUNT_TYPES = [
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    roleCodes: ['SUPER_ADMIN'],
  },
  {
    code: 'EXECUTIVE',
    name: 'Executive',
    roleCodes: ['CMD', 'CEO'],
  },
  {
    code: 'MANAGEMENT',
    name: 'Management',
    roleCodes: [
      'GENERAL_MANAGER',
      'DEPARTMENT_HEAD',
      'BRANCH_MANAGER',
      'OPERATIONS_MANAGER',
      'CCTV_OPERATOR',
      'CONTROL_ROOM',
    ],
  },
  {
    code: 'HR',
    name: 'HR',
    roleCodes: ['HR_OFFICER'],
  },
  {
    code: 'PAYROLL',
    name: 'Payroll',
    roleCodes: ['PAYROLL_OFFICER'],
  },
  {
    code: 'FINANCE',
    name: 'Finance',
    roleCodes: ['ACCOUNTS_OFFICER'],
  },
  {
    code: 'PROCUREMENT',
    name: 'Procurement',
    roleCodes: ['PROCUREMENT_OFFICER', 'STOREKEEPER'],
  },
  {
    code: 'GUARD',
    name: 'Guard',
    roleCodes: ['GUARD'],
  },
  {
    code: 'SUPERVISOR',
    name: 'Supervisor',
    roleCodes: ['SUPERVISOR', 'FIELD_OFFICER', 'GATE_OFFICER'],
  },
  {
    code: 'CUSTOMER',
    name: 'Customer',
    roleCodes: ['CUSTOMER_PORTAL'],
  },
  {
    code: 'CUSTOMER_EMPLOYEE',
    name: 'Customer Employee',
    roleCodes: ['CUSTOMER_EMPLOYEE'],
  },
  {
    code: 'VISITOR',
    name: 'Visitor',
    roleCodes: ['CONTRACTOR', 'CONSULTANT', 'SERVICE_PROVIDER'],
  },
  {
    code: 'PARKING',
    name: 'Parking',
    roleCodes: ['PARKING_OFFICER', 'VEHICLE_OWNER'],
  },
  {
    code: 'SUPPLIER',
    name: 'Supplier',
    roleCodes: ['SUPPLIER_PORTAL'],
  },
  {
    code: 'APPLICANT',
    name: 'Applicant',
    roleCodes: [] as string[],
  },
  {
    code: 'OTHER_SECURITY_COMPANY',
    name: 'Other Security Company',
    roleCodes: ['OTHER_SECURITY_COMPANY'],
  },
  {
    code: 'MARKETING_AGENT',
    name: 'Marketing Agent',
    roleCodes: ['MARKETING'],
  },
  {
    code: 'SUPPORT_AGENT',
    name: 'Support Agent',
    roleCodes: ['CALL_CENTRE', 'IT_SUPPORT'],
  },
  {
    code: 'COMPLIANCE',
    name: 'Compliance',
    roleCodes: [
      'COMPLIANCE_OFFICER',
      'DPO',
      'CISO',
      'INTERNAL_AUDITOR',
      'LEGAL',
    ],
  },
  {
    code: 'DEVELOPER',
    name: 'Developer',
    roleCodes: ['DEVELOPER'],
  },
] as const;

export type DesignAccountTypeCode = (typeof DESIGN_ACCOUNT_TYPES)[number]['code'];

export const DESIGN_PORTALS = [
  {
    id: '35.1',
    name: 'Super Admin',
    primaryUsers: 'Super Admin, ICT, DBA, CISO',
    job: 'Users, roles, branches, modules, approvals, backups, audit',
    entry: 'admin-web /superadmin',
    gatePermissions: ['users.manage'],
    accountTypeCodes: ['SUPER_ADMIN', 'SUPPORT_AGENT', 'COMPLIANCE', 'MANAGEMENT'],
    roleCodes: ['SUPER_ADMIN', 'IT_SUPPORT', 'CISO', 'GENERAL_MANAGER'],
    security:
      'RBAC users.manage; A6 privileged ceiling; role/suspend via approval for IT; password policy GM/SA.',
  },
  {
    id: '35.2',
    name: 'Executive Dashboard',
    primaryUsers: 'CMD, CEO, GM, Department Heads',
    job: 'Company-wide KPIs, revenue, contracts, risks, compliance',
    entry: 'executive-web :3001',
    gatePermissions: ['reporting.read'],
    accountTypeCodes: ['EXECUTIVE', 'MANAGEMENT', 'COMPLIANCE'],
    roleCodes: ['CMD', 'CEO', 'GENERAL_MANAGER', 'DEPARTMENT_HEAD', 'LEGAL'],
    security: 'reporting.read; payroll KPIs from immutable snapshots only; org-scoped.',
  },
  {
    id: '35.3',
    name: 'Administration',
    primaryUsers: 'GM, Admin, Branch/Dept Heads',
    job: 'Company/branch records, files, office ops',
    entry: 'admin-web /administration',
    gatePermissions: ['enterprise.manage'],
    accountTypeCodes: ['MANAGEMENT'],
    roleCodes: ['GENERAL_MANAGER', 'DEPARTMENT_HEAD', 'BRANCH_MANAGER'],
    security: 'enterprise.manage; file cabinets need documents.manage + parent domain perm.',
  },
  {
    id: '35.4',
    name: 'HR & Employee Management',
    primaryUsers: 'HR, Recruitment, Training',
    job: 'Profiles, leave, discipline, training, onboarding',
    entry: 'admin-web /hr',
    gatePermissions: ['hr.manage'],
    accountTypeCodes: ['HR', 'MANAGEMENT'],
    roleCodes: ['HR_OFFICER', 'DEPARTMENT_HEAD'],
    security: 'hr.manage; movements creator ≠ approver via shared approvals.',
  },
  {
    id: '35.5',
    name: 'Employee Self-Service',
    primaryUsers: 'All employees with an HR profile',
    job: 'Own profile, payslips, leave, loans, equipment, requests',
    entry: 'admin-web /ess',
    gatePermissions: ['ess.access'],
    accountTypeCodes: ['GUARD', 'SUPERVISOR', 'HR', 'MANAGEMENT', 'FINANCE', 'PAYROLL'],
    roleCodes: ['GUARD', 'SUPERVISOR', 'HR_OFFICER'],
    security: 'Self-scoped to linked Employee; ESS_PROFILE_MISSING if unlinked; act on /approvals.',
  },
  {
    id: '35.6',
    name: 'Guard Mobile App',
    primaryUsers: 'Guards',
    job: 'Attendance, alertness, patrols, parking patrol, incidents',
    entry: 'mobile/guard-app',
    gatePermissions: ['attendance.manage'],
    accountTypeCodes: ['GUARD'],
    roleCodes: ['GUARD'],
    security: 'GUARD self-scope; own records only; site ABAC; no visitors.manage.',
  },
  {
    id: '35.7',
    name: 'Supervisor Mobile App',
    primaryUsers: 'Supervisors, Field Officers, BOM',
    job: 'Verify attendance/alertness, inspections, replacements',
    entry: 'mobile/supervisor-app',
    gatePermissions: ['attendance.manage', 'operations.manage'],
    accountTypeCodes: ['SUPERVISOR', 'MANAGEMENT'],
    roleCodes: ['SUPERVISOR', 'FIELD_OFFICER', 'BRANCH_MANAGER', 'OPERATIONS_MANAGER'],
    security: 'JWT allowedSiteIds; GUARD login rejected; creator ≠ approver on EOB/attendance.',
  },
  {
    id: '35.8',
    name: 'Customer Portal',
    primaryUsers: 'Customer admins / HR / security / finance',
    job: 'Contracts, invoices, guards, SLA, own data only',
    entry: 'customer-web :3002',
    gatePermissions: ['contracts.manage'],
    accountTypeCodes: ['CUSTOMER'],
    roleCodes: ['CUSTOMER_PORTAL'],
    security: 'CustomerPortalGuard + JWT customerId; CUSTOMER_PORTAL_SCOPE_REQUIRED; own org only.',
  },
  {
    id: '35.9',
    name: 'Customer Employee Access',
    primaryUsers: 'Customer employees + their admins',
    job: 'Access/attendance via QR/bio/card/PIN — own org only',
    entry: 'customer-web /my-access',
    gatePermissions: ['access.self'],
    accountTypeCodes: ['CUSTOMER_EMPLOYEE', 'CUSTOMER'],
    roleCodes: ['CUSTOMER_EMPLOYEE'],
    security: 'access.self vs access.manage; site grants; never mixed with guard attendance.',
  },
  {
    id: '35.10',
    name: 'Visitor Appointment',
    primaryUsers: 'Guests, contractors, consultants, candidates, suppliers visiting',
    job: 'Online appointment → host approve → verification code',
    entry: 'visitor-web :3005',
    gatePermissions: [],
    accountTypeCodes: ['VISITOR'],
    roleCodes: ['CONTRACTOR', 'CONSULTANT', 'SERVICE_PROVIDER'],
    security:
      'Public book (no login); E4/E5/E6 self-scope; gate code hashed, issued after approve; creator ≠ approver.',
    publicAccess: true,
  },
  {
    id: '35.11',
    name: 'Gate Verification App',
    primaryUsers: 'Gate officers, guards, supervisors',
    job: 'Codes, cards, parking permits, vehicle entry',
    entry: 'mobile/gate-verification-app',
    gatePermissions: ['visitors.manage'],
    accountTypeCodes: ['SUPERVISOR'],
    roleCodes: ['GATE_OFFICER'],
    security: 'visitors.manage; portal JWT cannot gate-verify; deny → FieldAlert.',
  },
  {
    id: '35.12',
    name: 'Parking Management',
    primaryUsers: 'Parking admins, gate, customer security',
    job: 'Vehicles, permits, violations, billing, blacklist',
    entry: 'parking-web :3006',
    gatePermissions: ['parking.manage'],
    accountTypeCodes: ['PARKING', 'CUSTOMER'],
    roleCodes: ['PARKING_OFFICER'],
    security: 'parking.manage vs parking.self (owner); ANPR results only — no Nest video.',
  },
  {
    id: '35.13',
    name: 'Recruitment',
    primaryUsers: 'Applicants + HR / panels',
    job: 'Apply, documents, interview, onboarding',
    entry: 'recruitment-web :3004 + admin-web /hr/applications',
    gatePermissions: ['recruitment.manage'],
    accountTypeCodes: ['APPLICANT', 'HR'],
    roleCodes: ['HR_OFFICER'],
    security: 'Public apply/status (no PII leak); staff inbox recruitment.manage.',
    publicAccess: true,
  },
  {
    id: '35.14',
    name: 'Other Security Company',
    primaryUsers: 'Registered other security companies',
    job: 'Register, request guard recruitment by count/qualifications/location/training/urgency/terms',
    entry: 'recruitment-web /partner',
    gatePermissions: ['recruitment.b2b'],
    accountTypeCodes: ['OTHER_SECURITY_COMPANY'],
    roleCodes: ['OTHER_SECURITY_COMPANY'],
    security: 'JWT b2bPartnerId; OtherSecurityPortalGuard; requests until partner APPROVED.',
  },
  {
    id: '35.15',
    name: 'Finance & Accounts',
    primaryUsers:
      'Finance Director, Chief Accountant, Accountants, Cashiers, authorized management (seeded ACCOUNTS_OFFICER + GM/CEO/CMD). Payroll Officers use 35.16. Internal Auditor uses Compliance (audit.read) — not finance.manage.',
    job: 'Invoices, receipts, customer/parking payments, petty cash, AP payment vouchers, live finance reports. Payroll/loan deductions → 35.16. Bank recon deferred.',
    entry: 'admin-web /finance',
    gatePermissions: ['finance.manage'],
    accountTypeCodes: ['FINANCE', 'MANAGEMENT'],
    roleCodes: ['ACCOUNTS_OFFICER', 'GENERAL_MANAGER'],
    security:
      'finance.manage; petty cash creator ≠ issuer; payment voucher creator ≠ approver/payer; no extra CASHIER/FINANCE_DIRECTOR roles.',
  },
  {
    id: '35.16',
    name: 'Payroll',
    primaryUsers:
      'Payroll Officers, HR Officers, Finance Officers, approving management (PAYROLL_OFFICER / HR_OFFICER / ACCOUNTS_OFFICER + GM/CEO/CMD). Customer payroll officers use customer-web /payroll — not a new IAM role.',
    job: 'Company + customer-managed payroll, OT/allowances/alertness/loans/statutory on immutable snapshots, e-payroll due alerts, payslips, bank/mobile files. Approval before pay.',
    entry: 'admin-web /payroll',
    gatePermissions: ['payroll.manage'],
    accountTypeCodes: ['PAYROLL', 'HR', 'FINANCE', 'MANAGEMENT'],
    roleCodes: ['PAYROLL_OFFICER', 'HR_OFFICER', 'ACCOUNTS_OFFICER', 'GENERAL_MANAGER'],
    security:
      'Immutable PayslipSnapshot; payroll-approval HR→Finance→GM→CEO; creator ≠ approver; customer cycles isolated; e-payroll due only if invoice PAID.',
  },
  {
    id: '35.17',
    name: 'Supplier Portal',
    primaryUsers:
      'Registered suppliers and vendors (SUPPLIER_PORTAL). Procurement officers use 35.18 admin-web /procurement — they do not log into supplier-web. Site contractors / service providers use visitor-web (35.10 / E4–E6), not this vendor portal.',
    job: 'Register, upload business documents, submit quotations, receive issued POs, upload invoices, submit delivery notes, track payment status, message procurement.',
    entry: 'supplier-web :3003',
    gatePermissions: ['procurement.manage'],
    accountTypeCodes: ['SUPPLIER'],
    roleCodes: ['SUPPLIER_PORTAL'],
    security:
      'JWT supplierId + SupplierPortalGuard fail-closed; own data only; quotes locked until APPROVED; issued POs only (no DRAFT). Gate perm string is the portal role, not staff org-wide procurement.',
  },
  {
    id: '35.18',
    name: 'Procurement & Inventory',
    primaryUsers:
      'Procurement Manager / Officers mapped to seeded PROCUREMENT_OFFICER (procurement1@). Storekeepers (STOREKEEPER / store1@) for GRN + stock + issued assets. Finance Officers stay Portal 35.15 (AP vouchers) — not granted procurement.manage. Branch Managers stay Field Ops; they do not get org-wide buying mutate on seed. Authorized PR/PO approvers = GM on /approvals. Vendors use 35.17.',
    job: 'Purchase requests, supplier comparison, purchase orders, GRNs, bulk stock (uniforms, boots, smartphones, radios, CCTV, parking, office), issued assets on /assets.',
    entry: 'admin-web /procurement',
    gatePermissions: ['procurement.manage', 'inventory.manage'],
    accountTypeCodes: ['PROCUREMENT'],
    roleCodes: ['PROCUREMENT_OFFICER', 'STOREKEEPER'],
    security:
      'PR/PO creator ≠ approver; award SoD; GRN inventory.manage OR procurement.manage; supplier approve creator ≠ approver; no PROCUREMENT_MANAGER role.',
  },
  {
    id: '35.19',
    name: 'Marketing & BD',
    primaryUsers:
      'Marketing Manager / BD Officers / Marketing Officers / Sales Agents mapped to seeded MARKETING (marketing1@). Referral Partners are named on the lead (STAFF / CUSTOMER / PARTNER / OTHER) — no REFERRAL_PARTNER login. Branch Managers stay Field Ops (no marketing.manage on seed). Authorized contract approvers remain Legal→GM→CEO→CMD on /approvals.',
    job: 'Leads, site surveys, quotations/proposals, sales pipeline, campaigns, referrals, commission register, convert to customer + DRAFT contract.',
    entry: 'admin-web /marketing',
    gatePermissions: ['marketing.manage'],
    accountTypeCodes: ['MARKETING_AGENT'],
    roleCodes: ['MARKETING'],
    security:
      'marketing.manage on pipeline (not customers.manage). Accounts/Finance keep CRM pickers without BD mutate. Contract convert via ContractsService DRAFT; creator ≠ approver on contract-approval. No MARKETING_MANAGER / SALES_AGENT roles.',
  },
  {
    id: '35.20',
    name: 'Call Centre / Support',
    primaryUsers:
      'Call Centre Agents / Customer Support Officers mapped to seeded CALL_CENTRE (callcentre1@). Helpdesk Officers stay IT_SUPPORT (it1@ — Super Admin users/notifications). Supervisors stay Branch Ops (/branch) for field incidents. GATE_OFFICER also holds visitors.manage so they can open this portal. No SUPPORT_OFFICER / HELPDESK roles.',
    job: 'Customer complaints, visitor appointment/gate support, parking/supplier/payroll inquiries as tickets, incident escalation via IncidentsService, service tickets.',
    entry: 'admin-web /callcentre',
    gatePermissions: ['visitors.manage'],
    accountTypeCodes: ['SUPPORT_AGENT'],
    roleCodes: ['CALL_CENTRE', 'GATE_OFFICER'],
    security:
      'Gate visitors.manage. Tickets/complaints allowlisted visitors.manage OR customers.manage. No parking.manage / payroll.manage / procurement.manage / incidents.manage on CALL_CENTRE. Ticket process creator ≠ processor. Escalate uses IncidentsService (not incidents HTTP). Parking/supplier/payroll are ticket categories, not those ledgers.',
  },
  {
    id: '35.21',
    name: 'Compliance / Audit / DPO',
    primaryUsers:
      'Data Protection Officer (DPO / dpo1@), Compliance Officer (COMPLIANCE_OFFICER / compliance1@), Legal Officer (LEGAL / legal1@), Internal Auditor (INTERNAL_AUDITOR / auditor1@), CISO (ciso1@), and authorized management (GM/CEO/CMD / Dept Head). IT Support stays Super Admin helpdesk (it1@) — not this desk. No extra RISK_OFFICER / DPO_ASSISTANT roles.',
    job: 'Data-protection compliance (consents + policies), audit logs, user access (login history), incident reports (read-only), DPO breach register, legal documents / published policies, contract inventory, regulatory requirement catalog, thin risk register, policy compliance workflow.',
    entry: 'admin-web /compliance',
    gatePermissions: ['audit.read', 'compliance.manage', 'dpo.manage'],
    accountTypeCodes: ['COMPLIANCE'],
    roleCodes: [
      'DPO',
      'COMPLIANCE_OFFICER',
      'CISO',
      'INTERNAL_AUDITOR',
      'LEGAL',
    ],
    security:
      'Breach/consent mutate dpo.manage; policies compliance.manage (creator ≠ approver on policy-change-approval); risk mutate CO/DPO; auditor/legal read. IAM mutate stays Super Admin. Incident close stays Branch Ops. IT_SUPPORT audit.read may see the audit strip only (GOVERNANCE_DESK_DENIED on reports/registers).',
  },
  {
    id: '35.22',
    name: 'CCTV / Security Monitoring',
    primaryUsers:
      'CCTV Operators (CCTV_OPERATOR / cctv1@), Security Monitoring Officers mapped to CONTROL_ROOM (control1@), Operations Managers (ops1@). Supervisors stay Branch Ops (/branch) — no cctv.manage on SUPERVISOR. Authorized customer users stay customer-web (own data). No MONITORING_OFFICER / ALARM_OPERATOR roles.',
    job: 'Monitor CCTV wall (NVR embed/metadata), AI alerts (ack + 28-A incident), parking areas, customer-employee access + visitor gate denies, patrol scans / PATROL_MISSED, FieldAlert alarms, open security incidents. Video not via Nest.',
    entry: 'admin-web /cctv',
    gatePermissions: ['cctv.manage'],
    accountTypeCodes: ['MANAGEMENT'],
    roleCodes: ['CCTV_OPERATOR', 'CONTROL_ROOM', 'OPERATIONS_MANAGER'],
    security:
      'cctv.manage only on this portal. CCTV_OPERATOR is not granted parking.manage / access.manage / attendance.manage / incidents.manage — monitors via GET /cctv/*. ANPR decide stays parking|ops. Customer CCTV subdomain deferred. Org-wide mosaic (CCTV_OPERATOR in ORG_WIDE_SITE_VIEW_ROLES).',
  },
  {
    id: '35.23',
    name: 'Branch Operations',
    primaryUsers:
      'Regional / company-wide field mapped to OPERATIONS_MANAGER (ops1@); Branch Managers / Branch Operations Managers mapped to BRANCH_MANAGER (bom1@); Field Officers (field1@); Supervisors (supervisor1@) for site duty. Technical Managers stay CCTV / Devices (no TECHNICAL_MANAGER role). Business Development stays Marketing (35.19) — MARKETING is not granted operations.manage. No REGIONAL_MANAGER / BOM extra role.',
    job: 'Branch staff on post, customer sites, guard deployment, attendance & alertness, inspections (EOB comments/handover), incidents, parking monitor, petty cash requests, field reports & branch performance (34-A pack).',
    entry: 'admin-web /branch',
    gatePermissions: ['operations.manage'],
    accountTypeCodes: ['MANAGEMENT', 'SUPERVISOR'],
    roleCodes: [
      'OPERATIONS_MANAGER',
      'BRANCH_MANAGER',
      'FIELD_OFFICER',
      'SUPERVISOR',
    ],
    security:
      'Site ABAC via allowedSiteIds (BOM branch→sites at login). GUARD cannot admin. Parking mutate stays parking.manage. Petty cash approve/issue stays finance.manage (creator ≠ issuer). HR hire/exit stays hr.manage.',
  },
  {
    id: '35.24',
    name: 'Developer / Integration',
    primaryUsers:
      'Software Developers / System Integrators mapped to seeded DEVELOPER (dev1@). ICT Manager / API Administrators use SUPER_ADMIN or GM (allPerms) — no API_ADMIN / ICT_MANAGER. IT Support (it1@) stays Super Admin helpdesk. No TECHNICAL_PARTNER login.',
    job: 'APIs (Swagger hosts), adapters, webhooks, outbox, environments, logs, ping tests, biometric/CCTV/RFID/ANPR registry counts, CSV export of integration logs. Banks / mobile money / Meta WhatsApp / MQTT Nest client / bulk import deferred.',
    entry: 'admin-web /developer',
    gatePermissions: ['integrations.manage'],
    accountTypeCodes: ['DEVELOPER', 'SUPER_ADMIN', 'MANAGEMENT'],
    roleCodes: ['DEVELOPER', 'SUPER_ADMIN', 'GENERAL_MANAGER'],
    security:
      'integrations.manage. Browser never holds INTEGRATION_SERVICE_TOKEN. Config/logs/export omit secrets and payloads. DEVELOPER has no users.manage. Webhook replay FAILED/DLQ only; outbox PENDING/FAILED only. CCTV video stays on NVR.',
  },
] as const;
